### ISSUE TITLE
Files API is missing

### ISSUE THREAD

**Issue by timini** [complexbear/terraform-provider-opencga#6]
Thanks for the work so far, it seems the files API is missing.

I was thinking of implementing it to allow registering of reference genomes.

Would you have any pointers for getting going with that?

**Comment by complexbear** [comment]
Interesting idea @timini.

Yes, I think this is a good use case for populating studies with reference content.
Apologies for the slow reply, I wasn't monitoring the issues here.

You can take an existing resource as an example (perhaps the study acls).
It would need
* A new File type in `opencga_types.go`
* A new resource `opencga_file.go`
* The new resource added to the `provider.go`
* Update `/docs`

Not sure how familiar you are with Go / Terraform providers. Let me know if I can help.

**Comment by complexbear** [comment]
Provided for in v0.4.0
